# Generated by Django 3.1.7 on 2021-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
