# Generated by Django 3.1.7 on 2021-05-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_playlistsongrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlistsongrelation',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_relation', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistsongrelation',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_relation', to='music.song'),
        ),
    ]
