# Generated by Django 3.1.7 on 2021-05-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210502_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsongrelation',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_song_relation', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='playlistsongrelation',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_playlist_relation', to='music.song'),
        ),
    ]
